default_agent: literacy_assessment
agents:
  literacy_assessment:
    name: literacy_assessment
    entrypoint: /Users/john.ruiz/Documents/projects/deepagents/deploy/agentcore_literacy_assessment/serve_bedrock.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::961105418118:role/agentcore-literacy_assessment-role-0511
      execution_role_auto_create: false
      account: '961105418118'
      region: eu-central-1
      ecr_repository: 961105418118.dkr.ecr.eu-central-1.amazonaws.com/bedrock-agentcore-literacy_assessment
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: literacy_assessment-nOAwV9Bfmp
      agent_arn: arn:aws:bedrock-agentcore:eu-central-1:961105418118:runtime/literacy_assessment-nOAwV9Bfmp
      agent_session_id: 51cf0f08-d7ab-4a40-a921-5f924719d41a
    codebuild:
      project_name: bedrock-agentcore-literacy_assessment-builder
      execution_role: arn:aws:iam::961105418118:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-central-1-5af9491001
      source_bucket: bedrock-agentcore-codebuild-sources-961105418118-eu-central-1
    authorizer_configuration: null
    oauth_configuration: null
